_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
arch:
    value: resnet
batch_size_train:
    value: 24
batch_size_val:
    value: 8
dataset_root:
    value: ../data/UT_HAR_OG
learning_rate:
    value: 0.0001
num_classes:
    value: 8
num_epochs:
    value: 30
optimizer:
    value: NAdam
