_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
arch:
    value: lstm
batch_size_train:
    value: 24
batch_size_val:
    value: 8
bidirectional:
    value: false
dataset_root:
    value: /home/francisco.m.ribeiro/PDEEC/ML/Project/hybrid-wifi-har/data/UT_HAR_OG
hidden_dim:
    value: 64
learning_rate:
    value: 0.0001
normalize:
    value: true
num_classes:
    value: 8
num_epochs:
    value: 30
num_layers:
    value: 1
optimizer:
    value: NAdam
test_split:
    value: 0.2
val_split:
    value: 0.2
